SETTINGS:
  # number of concurrent threads
  THREADS: 1

  # number of retries for ANY action
  ATTEMPTS: 5

  # pause between attempts
  PAUSE_BETWEEN_ATTEMPTS: [5, 15]

  PAUSE_BETWEEN_SWAPS: [30, 60]

  # pause in seconds between accounts
  RANDOM_PAUSE_BETWEEN_ACCOUNTS: [3, 10]

  # pause in seconds between actions
  RANDOM_PAUSE_BETWEEN_ACTIONS: [2, 5]

  
# --------------------------- #
FLOW:
  # tasks to do.
  # "connect_discord" - connect discord account
  # "swaps" - swaps tokens
  # "apriori" - stake MON token
  # "magma" - stake MON token on Magma
  # "owlto" - deploy contract on Owlto
  # "bima" - lending and faucet

  # Example: tasks: ["connect_discord", "swaps"]
  TASKS: ["bima"]

  # number of swaps on monad.xyz
  NUMBER_OF_SWAPS: [1, 3]

  # percent of balance to swap on monad.xyz
  PERCENT_OF_BALANCE_TO_SWAP: [10, 15]


APRIORI:
  AMOUNT_TO_STAKE: [0.0001, 0.0003]

MAGMA:
  AMOUNT_TO_STAKE: [0.0001, 0.0003]

BIMA:
  LEND: true
  PERCENT_OF_BALANCE_TO_LEND: [20, 30]
  