SETTINGS:
  # number of concurrent threads
  THREADS: 1

  # number of retries for ANY action
  ATTEMPTS: 5

  # account range. 
  # BY DEFAULT: [0, 0] - all accounts
  # [3, 5] - only 3 4 5 accounts
  # [7, 7] - only 7 account
  ACCOUNTS_RANGE: [0, 0]

  # pause between attempts
  PAUSE_BETWEEN_ATTEMPTS: [5, 15]

  # pause between swaps
  PAUSE_BETWEEN_SWAPS: [10, 20]

  # pause in seconds between accounts
  RANDOM_PAUSE_BETWEEN_ACCOUNTS: [1, 5]

  # pause in seconds between actions
  RANDOM_PAUSE_BETWEEN_ACTIONS: [2, 5]

  # random pause before start of every account
  # to make sure that all accounts will be started at different times
  RANDOM_INITIALIZATION_PAUSE: [3, 10]

  # pause multiplier for browser actions
  BROWSER_PAUSE_MULTIPLIER: 3
  
# --------------------------- #
FLOW:
  # tasks to do.
  # "connect_discord" - connect discord account
  # "swaps" - swaps tokens
  # "apriori" - stake MON token
  # "magma" - stake MON token on Magma
  # "owlto" - deploy contract on Owlto
  # "bima" - lending and faucet
  # "faucet" - get tokens from faucet
  # "collect_all_to_monad" - swap all tokens to native token (MON)
  # "ambient" - swap tokens on Ambient DEX
  # "bean" - swap tokens on Bean DEX
  # "monadverse_mint" - mint Monadverse NFT - https://www.monadverse.land/mint
  # "logs" - show logs: MON balance | number of transactions | avarage balance | avarage number of transactions

  # Example: tasks: ["connect_discord", "swaps"]
  TASKS: ["swaps", "bean", "ambient", "collect_all_to_monad"]

  # number of swaps on monad.xyz
  NUMBER_OF_SWAPS: [1, 3]

  # percent of balance to swap on monad.xyz
  PERCENT_OF_BALANCE_TO_SWAP: [10, 15]


FAUCET:
  THIRDWEB: false
  MONAD_XYZ: true

  CAPSOLVER_API_KEY: "CAP-"
  PROXY_FOR_CAPTCHA: "user:pass@ip:port"


APRIORI:
  AMOUNT_TO_STAKE: [0.0001, 0.0003]

MAGMA:
  AMOUNT_TO_STAKE: [0.0001, 0.0003]

BIMA:
  LEND: true
  PERCENT_OF_BALANCE_TO_LEND: [20, 30]
  
